plugins {
    alias(libs.plugins.android.application)
}

def wechatAppId = "wxb47bc8f618cc1b59"
def wechatAppSecret = "84ae2dde3996c26339ad06c7c55345a8"

android {
    namespace 'com.justyn.travelmap'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "com.justyn.travelmap"
        minSdk 33
        targetSdk 36
        versionCode 1
        versionName "1.0"
        buildConfigField "String", "API_BASE_URL", "\"http://qcd76498.natappfree.cc\""
        buildConfigField "String", "WECHAT_APP_ID", "\"${wechatAppId}\""
        buildConfigField "String", "WECHAT_APP_SECRET", "\"${wechatAppSecret}\""
        resValue "string", "wechat_app_id", "\"${wechatAppId}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.recyclerview
    implementation libs.swiperefreshlayout
    implementation libs.glide
    implementation libs.shimmer
    annotationProcessor libs.glideCompiler
    implementation 'com.amap.api:3dmap:latest.integration'
    implementation 'com.tencent.mm.opensdk:wechat-sdk-android:6.8.0'
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
